// lib/timezone.js

exports.timezones = [
  ["Afghanistan", "Asia/Kabul"],
  ["Albania", "Europe/Tirane"],
  ["Algeria", "Africa/Algiers"],
  ["Argentina", "America/Argentina/Buenos_Aires"],
  ["Australia-Sydney", "Australia/Sydney"],
  ["Australia-Melbourne", "Australia/Melbourne"],
  ["Australia-Perth", "Australia/Perth"],
  ["Austria", "Europe/Vienna"],
  ["Azerbaijan", "Asia/Baku"],
  ["Bahrain", "Asia/Bahrain"],
  ["Bangladesh", "Asia/Dhaka"],
  ["Belarus", "Europe/Minsk"],
  ["Belgium", "Europe/Brussels"],
  ["Brazil-Sao_Paulo", "America/Sao_Paulo"],
  ["Brazil-Rio_de_Janeiro", "America/Rio_de_Janeiro"],
  ["Bulgaria", "Europe/Sofia"],
  ["Cambodia", "Asia/Phnom_Penh"],
  ["Canada-Toronto", "America/Toronto"],
  ["Canada-Vancouver", "America/Vancouver"],
  ["Chile", "America/Santiago"],
  ["China", "Asia/Shanghai"],
  ["Colombia", "America/Bogota"],
  ["Costa Rica", "America/Costa_Rica"],
  ["Croatia", "Europe/Zagreb"],
  ["Cuba", "America/Havana"],
  ["Cyprus", "Asia/Nicosia"],
  ["Czech Republic", "Europe/Prague"],
  ["Denmark", "Europe/Copenhagen"],
  ["Dominican Republic", "America/Santo_Domingo"],
  ["Ecuador", "America/Guayaquil"],
  ["Egypt", "Africa/Cairo"],
  ["Estonia", "Europe/Tallinn"],
  ["Ethiopia", "Africa/Addis_Ababa"],
  ["Finland", "Europe/Helsinki"],
  ["France", "Europe/Paris"],
  ["Georgia", "Asia/Tbilisi"],
  ["Germany", "Europe/Berlin"],
  ["Ghana", "Africa/Accra"],
  ["Greece", "Europe/Athens"],
  ["Guatemala", "America/Guatemala"],
  ["Honduras", "America/Tegucigalpa"],
  ["Hong Kong", "Asia/Hong_Kong"],
  ["Hungary", "Europe/Budapest"],
  ["Iceland", "Atlantic/Reykjavik"],
  ["India", "Asia/Kolkata"],
  ["Indonesia", "Asia/Jakarta"],
  ["Iran", "Asia/Tehran"],
  ["Iraq", "Asia/Baghdad"],
  ["Ireland", "Europe/Dublin"],
  ["Israel", "Asia/Jerusalem"],
  ["Italy", "Europe/Rome"],
  ["Jamaica", "America/Jamaica"],
  ["Japan", "Asia/Tokyo"],
  ["Jordan", "Asia/Amman"],
  ["Kazakhstan", "Asia/Almaty"],
  ["Kenya", "Africa/Nairobi"],
  ["Kuwait", "Asia/Kuwait"],
  ["Laos", "Asia/Vientiane"],
  ["Latvia", "Europe/Riga"],
  ["Lebanon", "Asia/Beirut"],
  ["Libya", "Africa/Tripoli"],
  ["Lithuania", "Europe/Vilnius"],
  ["Luxembourg", "Europe/Luxembourg"],
  ["Macau", "Asia/Macau"],
  ["Malaysia", "Asia/Kuala_Lumpur"],
  ["Maldives", "Indian/Maldives"],
  ["Malta", "Europe/Malta"],
  ["Mexico", "America/Mexico_City"],
  ["Mongolia", "Asia/Ulaanbaatar"],
  ["Morocco", "Africa/Casablanca"],
  ["Myanmar", "Asia/Yangon"],
  ["Nepal", "Asia/Kathmandu"],
  ["Netherlands", "Europe/Amsterdam"],
  ["New Zealand", "Pacific/Auckland"],
  ["Nigeria", "Africa/Lagos"],
  ["North Korea", "Asia/Pyongyang"],
  ["Norway", "Europe/Oslo"],
  ["Oman", "Asia/Muscat"],
  ["Pakistan", "Asia/Karachi"],
  ["Panama", "America/Panama"],
  ["Paraguay", "America/Asuncion"],
  ["Peru", "America/Lima"],
  ["Philippines", "Asia/Manila"],
  ["Poland", "Europe/Warsaw"],
  ["Portugal", "Europe/Lisbon"],
  ["Qatar", "Asia/Qatar"],
  ["Romania", "Europe/Bucharest"],
  ["Russia-Moscow", "Europe/Moscow"],
  ["Russia-Vladivostok", "Asia/Vladivostok"],
  ["Saudi Arabia", "Asia/Riyadh"],
  ["Senegal", "Africa/Dakar"],
  ["Serbia", "Europe/Belgrade"],
  ["Singapore", "Asia/Singapore"],
  ["Slovakia", "Europe/Bratislava"],
  ["Slovenia", "Europe/Ljubljana"],
  ["South Africa", "Africa/Johannesburg"],
  ["South Korea", "Asia/Seoul"],
  ["Spain", "Europe/Madrid"],
  ["Sri Lanka", "Asia/Colombo"],
  ["Sudan", "Africa/Khartoum"],
  ["Sweden", "Europe/Stockholm"],
  ["Switzerland", "Europe/Zurich"],
  ["Syria", "Asia/Damascus"],
  ["Taiwan", "Asia/Taipei"],
  ["Tanzania", "Africa/Dar_es_Salaam"],
  ["Thailand", "Asia/Bangkok"],
  ["Tunisia", "Africa/Tunis"],
  ["Turkey", "Europe/Istanbul"],
  ["Ukraine", "Europe/Kiev"],
  ["UAE", "Asia/Dubai"],
  ["UK", "Europe/London"],
  ["USA-New_York", "America/New_York"],
  ["USA-Los_Angeles", "America/Los_Angeles"],
  ["USA-Chicago", "America/Chicago"],
  ["Uruguay", "America/Montevideo"],
  ["Uzbekistan", "Asia/Tashkent"],
  ["Venezuela", "America/Caracas"],
  ["VietNam", "Asia/Ho_Chi_Minh"],
  ["Yemen", "Asia/Aden"],
  ["Zimbabwe", "Africa/Harare"]
];